<?php /** @var Dhl_ExpressRates_Block_Checkout_Onepage_Shipping_Method_Deliverydate $this */ ?>
<script type="text/javascript">
    //<![CDATA[
    /** @type {{code: string, delivery_date: string}[]} deliveryDates */
    var deliveryDates = <?php /* @noEscape */ echo $this->getEstimatedDeliveryDates() ?>;

    for (var i = 0; i < deliveryDates.length; ++i) {
        var labelElement = document.querySelector('label[for="s_method_' + deliveryDates[i].code + '"]');
        if (labelElement) {
            labelElement.insert(
                '<p><small>Estimated delivery: ' + deliveryDates[i].delivery_date + '</small></p>'
            );
        }
    }
    //]]>
</script>
